import { buildPushPayload, type PushSubscription } from "@block65/webcrypto-web-push";

type StoredSubscription = { id:string; endpoint:string; p256dh:string; auth:string; expiration_time:number|null };
type SubscriptionInput = { endpoint?:unknown; expirationTime?:unknown; keys?:{p256dh?:unknown;auth?:unknown} };
type NewMailPush = { id:string };
type VapidKeys = { publicKey:string; privateKey:string };

const VAPID_SUBJECT = "mailto:contact@liamthemo.com";
const BASE64URL = /^[A-Za-z0-9_-]+$/;
const MAX_ENDPOINT_LENGTH = 2048;
const PUSH_HOSTS = ["web.push.apple.com","fcm.googleapis.com","updates.push.services.mozilla.com","push.services.mozilla.com"];

function normalizeVapidKey(value:string|undefined):string{let normalized=(value??"").trim();for(const[open,close]of[["\"","\""],["'","'"],["“","”"],["‘","’"]]){if(normalized.startsWith(open)&&normalized.endsWith(close)){normalized=normalized.slice(open.length,-close.length).trim();break;}}return normalized.replace(/\s+/g,"").replace(/=+$/g,"");}
function vapidKeys(env:Env):VapidKeys|null{const publicKey=normalizeVapidKey(env.VAPID_PUBLIC_KEY),privateKey=normalizeVapidKey(env.VAPID_PRIVATE_KEY);return publicKey.length===87&&privateKey.length===43&&BASE64URL.test(publicKey)&&BASE64URL.test(privateKey)?{publicKey,privateKey}:null;}
function validEndpoint(value:string):boolean{if(!value||value.length>MAX_ENDPOINT_LENGTH)return false;try{const url=new URL(value);return url.protocol==="https:"&&url.username===""&&url.password===""&&url.port===""&&PUSH_HOSTS.includes(url.hostname.toLowerCase());}catch{return false;}}
export function pushConfig(env:Env):Response{const keys=vapidKeys(env);return Response.json({configured:Boolean(keys),publicKey:keys?.publicKey??null});}

export async function subscribePush(request:Request,env:Env):Promise<Response>{if(!vapidKeys(env))return Response.json({error:"Push notifications are not configured"},{status:503});const body=await request.json<SubscriptionInput>().catch(()=>null);if(!body)return Response.json({error:"Invalid subscription payload"},{status:400});const endpoint=typeof body.endpoint==="string"?body.endpoint.trim():"",p256dh=typeof body.keys?.p256dh==="string"?body.keys.p256dh.trim():"",auth=typeof body.keys?.auth==="string"?body.keys.auth.trim():"";const expirationTime=typeof body.expirationTime==="number"&&Number.isFinite(body.expirationTime)?Math.floor(body.expirationTime):null;if(!validEndpoint(endpoint)||p256dh.length<40||p256dh.length>128||auth.length<16||auth.length>64||!BASE64URL.test(p256dh)||!BASE64URL.test(auth))return Response.json({error:"Invalid push subscription"},{status:400});const now=new Date().toISOString(),id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO push_subscriptions (id,endpoint,p256dh,auth,expiration_time,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?6) ON CONFLICT(endpoint) DO UPDATE SET p256dh=excluded.p256dh,auth=excluded.auth,expiration_time=excluded.expiration_time,updated_at=excluded.updated_at`).bind(id,endpoint,p256dh,auth,expirationTime,now).run();return Response.json({ok:true},{status:201});}
export async function unsubscribePush(request:Request,env:Env):Promise<Response>{const body=await request.json<{endpoint?:unknown}>().catch(()=>null),endpoint=typeof body?.endpoint==="string"?body.endpoint.trim():"";if(!validEndpoint(endpoint))return Response.json({error:"Invalid endpoint"},{status:400});await env.DB.prepare("DELETE FROM push_subscriptions WHERE endpoint = ?1").bind(endpoint).run();return Response.json({ok:true});}

async function sendToSubscription(env:Env,row:StoredSubscription,notification:NewMailPush):Promise<void>{const keys=vapidKeys(env);if(!keys||!validEndpoint(row.endpoint))return;const subscription:PushSubscription={endpoint:row.endpoint,expirationTime:row.expiration_time,keys:{p256dh:row.p256dh,auth:row.auth}};const payload=await buildPushPayload({data:JSON.stringify({title:"LTM Mails",body:"New email received",tag:`message-${notification.id}`,url:"/"}),options:{ttl:3600}},subscription,{subject:VAPID_SUBJECT,publicKey:keys.publicKey,privateKey:keys.privateKey});const response=await fetch(row.endpoint,payload);if(response.status===404||response.status===410){await env.DB.prepare("DELETE FROM push_subscriptions WHERE endpoint = ?1").bind(row.endpoint).run();return;}if(!response.ok)console.warn("Push delivery failed",response.status);}
export async function sendNewMailPush(env:Env,notification:NewMailPush):Promise<void>{if(!vapidKeys(env))return;await env.DB.prepare("DELETE FROM push_subscriptions WHERE expiration_time IS NOT NULL AND expiration_time <= ?1").bind(Date.now()).run();const subscriptions=await env.DB.prepare("SELECT id,endpoint,p256dh,auth,expiration_time FROM push_subscriptions ORDER BY updated_at DESC LIMIT 10").all<StoredSubscription>();await Promise.allSettled(subscriptions.results.map(row=>sendToSubscription(env,row,notification)));}
