import { getGoogleAccessToken } from "./googleCredentials";
import type { MailProvider, ProviderListOptions, ProviderMessage, ProviderMutation, ProviderSendInput, ProviderSendResult } from "./types";

const API = "https://gmail.googleapis.com/gmail/v1/users/me";
type Header={name?:string;value?:string};
type Part={mimeType?:string;filename?:string;body?:{data?:string;attachmentId?:string;size?:number};parts?:Part[]};
type GmailMessage={id?:string;threadId?:string;labelIds?:string[];snippet?:string;internalDate?:string;payload?:Part&{headers?:Header[]}};
const enc=new TextEncoder();
const b64url=(bytes:Uint8Array)=>{let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")};
const decode=(value:string)=>{const s=value.replace(/-/g,"+").replace(/_/g,"/");const raw=atob(s+"=".repeat((4-s.length%4)%4));const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new TextDecoder().decode(bytes)};
const header=(m:GmailMessage,n:string)=>m.payload?.headers?.find(h=>h.name?.toLowerCase()===n.toLowerCase())?.value??"";
const addr=(v:string)=>{const m=v.match(/^(.*?)\s*<([^>]+)>$/);return m?{name:m[1].replace(/^"|"$/g,"").trim()||null,email:m[2].trim()}:{name:null,email:v.trim()}};
const addresses=(v:string)=>v.split(",").map(x=>addr(x).email).filter(Boolean);
function parts(part:Part|undefined,out:Part[]=[]){if(!part)return out;if(part.mimeType?.startsWith("text/")||part.filename)out.push(part);for(const p of part.parts??[])parts(p,out);return out}
function text(m:GmailMessage){const all=parts(m.payload),plain=all.find(p=>p.mimeType==="text/plain"&&p.body?.data),html=all.find(p=>p.mimeType==="text/html"&&p.body?.data),raw=plain?.body?.data?decode(plain.body.data):html?.body?.data?decode(html.body.data).replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">"):"";return raw.replace(/\s+\n/g,"\n").trim().slice(0,2_000_000)}
function item(m:GmailMessage):ProviderMessage{const labels=new Set(m.labelIds??[]),from=addr(header(m,"From")),sent=labels.has("SENT"),date=new Date(Number(m.internalDate)||Date.now()).toISOString();return{id:m.id??"",threadId:m.threadId??m.id??"",direction:sent?"outbound":"inbound",fromAddress:from.email,fromName:from.name,toAddresses:addresses(header(m,"To")),subject:header(m,"Subject")||"(no subject)",preview:m.snippet??"",receivedAt:date,sentAt:sent?date:null,isRead:!labels.has("UNREAD"),isStarred:labels.has("STARRED"),isArchived:!labels.has("INBOX")&&!labels.has("SENT")&&!labels.has("TRASH"),isDeleted:labels.has("TRASH"),hasAttachments:parts(m.payload).some(p=>Boolean(p.filename)),deliveryStatus:null,isDraft:false}}
function clean(v:string){return v.replace(/[\r\n]+/g," ").trim()}
function mime(input:ProviderSendInput,from:string){const lines=[`From: ${clean(from)}`,`To: ${input.to.map(clean).join(", ")}`];if(input.cc.length)lines.push(`Cc: ${input.cc.map(clean).join(", ")}`);if(input.bcc.length)lines.push(`Bcc: ${input.bcc.map(clean).join(", ")}`);lines.push(`Subject: ${clean(input.subject)}`,"MIME-Version: 1.0");for(const[k,v]of Object.entries(input.headers??{}))lines.push(`${clean(k)}: ${clean(v)}`);lines.push('Content-Type: text/plain; charset="UTF-8"',"Content-Transfer-Encoding: 8bit","",input.text);return lines.join("\r\n")}
async function call(env:Env,accountId:string,path:string,init:RequestInit={}){const token=await getGoogleAccessToken(env,accountId),headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${token}`);const r=await fetch(`${API}${path}`,{...init,headers});if(!r.ok)throw new Error(r.status===401?"Gmail account requires reconnection":"Gmail request failed");return r}
const q=(f:string)=>f==="inbox"?"in:inbox":f==="starred"?"is:starred":f==="sent"?"in:sent":f==="trash"?"in:trash":f==="archive"?"-in:inbox -in:sent -in:trash":"";
export async function gmailFullMessage(env:Env,accountId:string,id:string){const m=await(await call(env,accountId,`/messages/${encodeURIComponent(id)}?format=full`)).json<GmailMessage>(),base=item(m);return{...base,ccAddresses:addresses(header(m,"Cc")),bccAddresses:addresses(header(m,"Bcc")),bodyText:text(m)||base.preview,bodyHtmlAvailable:false,inReplyTo:header(m,"In-Reply-To")||null,references:header(m,"References")||null,deliveryError:null,attachments:[]}}
export async function gmailThread(env:Env,accountId:string,threadId:string){const t=await(await call(env,accountId,`/threads/${encodeURIComponent(threadId)}?format=full`)).json<{messages?:GmailMessage[]}>();return Promise.all((t.messages??[]).slice(-100).map(m=>gmailFullMessage(env,accountId,m.id??"")))}
export function gmailProvider(env:Env,accountId:string,email:string):MailProvider{return{kind:"gmail",accountId,address:email,async listMessages(o:ProviderListOptions){const query=[q(o.folder),o.search].filter(Boolean).join(" ");const l=await(await call(env,accountId,`/messages?maxResults=${Math.min(o.limit,50)}&q=${encodeURIComponent(query)}`)).json<{messages?:Array<{id:string}>}>();return Promise.all((l.messages??[]).map(async x=>item(await(await call(env,accountId,`/messages/${encodeURIComponent(x.id)}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject`)).json<GmailMessage>())))},async getMessage(id){try{return item(await(await call(env,accountId,`/messages/${encodeURIComponent(id)}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject`)).json<GmailMessage>())}catch{return null}},async patchMessage(id,m:ProviderMutation){if(m.isDeleted!==undefined){await call(env,accountId,`/messages/${encodeURIComponent(id)}/${m.isDeleted?"trash":"untrash"}`,{method:"POST"});return true}const add:string[]=[],remove:string[]=[];if(m.isRead!==undefined)(m.isRead?remove:add).push("UNREAD");if(m.isStarred!==undefined)(m.isStarred?add:remove).push("STARRED");if(m.isArchived!==undefined)(m.isArchived?remove:add).push("INBOX");await call(env,accountId,`/messages/${encodeURIComponent(id)}/modify`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({addLabelIds:add,removeLabelIds:remove})});return true},async sendMessage(input:ProviderSendInput):Promise<ProviderSendResult>{if(input.attachments.length)throw new Error("Gmail attachments are not available in this test build");const raw=b64url(enc.encode(mime(input,email))),r=await(await call(env,accountId,"/messages/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({raw})})).json<{id?:string}>();return{providerMessageId:r.id??null}}}}
