import { gmailProvider } from "./gmailProvider";
import { nativeProvider } from "./native";
import type { MailProvider, MailProviderKind } from "./types";
export type ConnectedAccount={id:string;provider:MailProviderKind;emailAddress:string;displayName:string|null;status:"active"|"reauth_required"|"disabled";lastSyncedAt:string|null};
type AccountRow={id:string;provider:MailProviderKind;email_address:string;display_name:string|null;status:ConnectedAccount["status"];last_synced_at:string|null};
export const NATIVE_ACCOUNT_ID="native:primary";
export async function ensureNativeAccount(env:Env){await env.DB.prepare(`INSERT INTO connected_accounts (id,provider,provider_account_id,email_address,display_name,status,updated_at) VALUES (?1,'native',?1,?2,'LTM Email','active',CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET email_address=excluded.email_address,status='active',updated_at=CURRENT_TIMESTAMP`).bind(NATIVE_ACCOUNT_ID,env.PRIMARY_ADDRESS).run()}
export async function listConnectedAccounts(env:Env):Promise<ConnectedAccount[]>{await ensureNativeAccount(env);const r=await env.DB.prepare(`SELECT id,provider,email_address,display_name,status,last_synced_at FROM connected_accounts WHERE status!='disabled' ORDER BY CASE provider WHEN 'native' THEN 0 ELSE 1 END,created_at ASC`).all<AccountRow>();return r.results.map(x=>({id:x.id,provider:x.provider,emailAddress:x.email_address,displayName:x.display_name,status:x.status,lastSyncedAt:x.last_synced_at}))}
export async function resolveProvider(env:Env,accountId?:string|null):Promise<MailProvider|null>{const id=accountId?.trim()||NATIVE_ACCOUNT_ID;if(id===NATIVE_ACCOUNT_ID)return nativeProvider(env);const a=await env.DB.prepare("SELECT provider,status,email_address FROM connected_accounts WHERE id=?1 LIMIT 1").bind(id).first<{provider:MailProviderKind;status:string;email_address:string}>();if(!a||a.status!=="active")return null;if(a.provider==="gmail")return gmailProvider(env,id,a.email_address);return null}
